name: Generate Gameboy Contributions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Listar arquivos (Debug)
        run: ls -la  # <--- Isso vai mostrar no log se o template está lá
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Run Python Script
        run: python build_gameboy.py
        
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: Gameboy"
          file_pattern: "gameboy_contrib.svg"
